# Site Settings
title: Valdis Zobēla
url: 'http://zobela.eu'
baseurl: '' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Valdis Zobēla
tagline: Software Architect & Full Stack Developer
# pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: #>
  # <p>I'm a software and web developer.</p>

  # <p>My main expertise is in Python and JavaScript, but I'm open
  # for new languages and technologies and expanding my knowledge
  # stack. I'm using various frameworks, libraries and technologies
  # and trying to choose the best ones for a project (or new for
  # pet-projects). Programming is not only a job for me but also a
  # hobby.</p>

  # <p>I also have experience in Puzzle and Game design, especially
  # in coding puzzles and games. All my projects are located at
  # Github and I actively use it for my work and open source
  # contributions. My free time I spend at competition sites for
  # developers with interesting technical and algorithmic problems.</p>

#sidebar links
email: ue.aleboz@sidlav
phone: '+371 2836 3163'
website: zobela.eu #do not add http://
linkedin: valdiszobela
github: valdisz
twitter: '@valdis_zobela'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: False

# Tracker
analytics: UA-116315949-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
